blog/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailView, ArticleEditAdminView, ArticleCreateAdminView, ArticleDeleteAdminView

app_name = 'blog'

urlpatterns = [
    
    path('', ArticleListView.as_view(), name='home'),
    path('article/<int:id_article>', ArticleDetailView.as_view(), name='detail'),
    path('article/edit/<int:pk>', ArticleEditAdminView.as_view(), name='update'),
    path('article/new', ArticleCreateAdminView.as_view(), name='create'),
    path('article/delete/<int:pk>', ArticleDeleteAdminView.as_view(), name='delete')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name="Home"),
    
    path('accounts/', include('django.contrib.auth.urls'), name="Accounts"),
    
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models

class Article(models.Model):
    title=models.CharField(max_length=20)
    content=models.TextField()
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Article

class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model=Article
        fields=('title','content')
    

blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic.base import View
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import Article
from .forms import ArticleCreateForm

class ArticleListView(View):
    def get(self, request, *args, **kwargs):
        articles = Article.objects.all()
        context = {
            'articles': articles,
        }
        return render(request, 'blog/article_list.html', context)
    
class ArticleDetailView(View):
    def get(self, request, id_article, *args, **kwargs):
        article = get_object_or_404(Article, pk=id_article)
        context = {
            'article': article
        }
        return render(request, 'blog/article_detail.html', context)

class ArticleCreateAdminView(View):
    def get(self, request, *args, **kwargs):
        form = ArticleCreateForm()
        context = {
            'form': form
        }
        return render(request, 'blog/article_create.html', context)
    
    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = ArticleCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')
                
                p, created = Article.objects.get_or_create(title=title, defaults={'content': content})
                p.save()
                return redirect('blog:home')
        context = {
            
        }
        return render(request, 'blog/article_create.html', context)
    
class ArticleEditAdminView(UpdateView):
    model = Article
    fields = ['title', 'content']
    template_name = 'blog/article_update.html'
    
    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kwargs={'pk':pk})
    
class ArticleDeleteAdminView(DeleteView):
    model = Article
    template_name='blog/article_delete.html'
    def get_success_url(self):
        return reverse_lazy('blog:home')
    
    

core/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context = {
            
        }
        return render(request, 'home.html', context)

templates/blog/article_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        <form action="" method="post"> 
            {% csrf_token %}
            title{{form.title}}
            <br>
            content{{form.content}}
            <button type="submit">Publish</button>
        </form>
    {% else %}
    <h2>Error 404: Not Found</h2>
    {% endif %}
</body>
</html>

templates/blog/article_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>blog</title>
</head>
<body>
    <p>Are you sure?</p>
    <form action="" method="post">
        {% csrf_token %}
        {{form}}
        <button type="submit">Yes</button>
        <a href="{% url "blog:home" %}">No</a>
    </form>
</body>
</html>

templates/blog/article_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{article.title}}</h1>
    <h2>{{article.created_at}}</h2>
    <p>{{article.content}}</p>
</body>
</html>

templates/blog/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <h1>Personal Blog</h1>
    {% if user.is_authenticated %}
        <a href="{% url "blog:create" %}">+ Add</a>
        {% for article in articles %}
            <table>
                <tr>
                <th><a href="{% url "blog:detail" article.id%}">{{article.title}}</a></th>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th><a href="{% url "blog:update" article.id%}">Update</a></th>
                <th><a href="{% url "blog:delete" article.id%}">Delete</a></th>
                </tr>
            </table>
        {% empty %}
            <p>No hay articulos publicados</p>
        {% endfor %}
    {% else %}
        {% for article in articles %}
            <table>
                <tr>
                <th><a href="{% url "blog:detail" article.id%}">{{article.title}}</a></th>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
                <th>{{article.created_at}}</th>
                </tr>
            </table>
        {% empty %}
            <p>No hay articulos publicados</p>
        {% endfor %}
    {% endif %}
</body>
</html>

templates/blog/article_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        <form action="" method="post"> 
            {% csrf_token %}
            title{{form.title}}
            <br>
            content{{form.content}}
            <button type="submit">Update</button>
        </form>
    {% else %}
    <h2>Error 404: Not Found</h2>
    {% endif %}
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personal Blog</title>
</head>
<body>
    <h1>Personal Blog</h1>
    <p>This is a personal blog to write and publish articles on various topics</p>
    {% if user.is_authenticated %}
        <li>User: {{ user.get_username }}</li>
        <form method="POST" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit">Cerrar sesión</button>
        </form>
    {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}">Iniciar sesión</a></li>
    {% endif %}
    
</body>
</html>